export const ADD_CARD = 'ADD_CARD';
export const CHANGE_CARD_BUN = 'CHANGE_CARD_BUN';
export const DELETE_CARD = 'DELETE_CARD';

export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT';
